#!/bin/bash

###Removes extra headers and duplicate lines from COLVAR files
###Used during umbrella sampling reweighting to clean COLVAR files for mbar.py reweighting script

for ((i=0; i<=72; i++)); do
    #removes ALL headers in a COLVAR file generated by Plumed.
	awk '!/#! FIELDS time d.x bb.bias/' colvar_multi_$i > tmpfile && mv tmpfile colvar_multi_$i
    #removes duplicate lines from starting with .cpt file for uniform datapoints when reweighting
    awk '!a[$1]++' colvar_multi_$i > tmpfile && mv tmpfile colvar_multi_$i
    
    #sed '$!N; /^\(.*\)\n\1$/!P; D' colvar_multi_$i > tmpfile && mv tmpfile colvar_multi_$i
done
